version: "3.7"

services:
    api:
        container_name: express-api
        build:
            context: .
            dockerfile: Dockerfile
            target: devAPi
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - node_modules_express:/app/node_modules
        command: npm run nm
    client:
        container_name: react-client
        build:
            context: .
            dockerfile: Dockerfile
            target: devClient
        ports:
            - 80:3000
        volumes:
            - ./client:/client
            - node_modules_react:/app/node_modules
        command: npm run start
volumes:
    node_modules_react:
    node_modules_express:
