version: "3.7"

services:
    production:
        working_dir: /express
        container_name: express-prod
        environment:
            - NODE_ENV=production
            - DB_NAME=express
            - DB_PORT=5432
            - DB_HOST=192.168.11.52
            - DB_USERNAME=express
            - DB_PASSWORD=admin
            - PORT=3000
            - JWT_SECRET=secret
        build:
            context: .
            args:
                - REACT_APP_BASE_URL=http://localhost
                - INLINE_RUNTIME_CHUNK=false
            dockerfile: Dockerfile
            target: prod
        ports:
            - 80:3000
        command: sh -c "yarn run production"
