version: "3.7"

services:
    api:
        container_name: express-api
        build:
            context: .
            dockerfile: Dockerfile
            target: devAPi
        ports:
            - 8080:8080
        volumes:
            - ./server:/server:rw
        command: sh -c "yarn && yarn nm"
    client:
        container_name: react-client
        build:
            context: .
            dockerfile: Dockerfile
            target: devClient
        ports:
            - 80:3000
        volumes:
            - ./client:/client:rw
        command: sh -c "yarn && yarn start"
