version: "3.7"

services:
    api:
        container_name: express_test
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        command: npm run nm
volumes:
    node_modules:
